package main

// usrHome will be changed to the current user's home dir
// * tested
var usrHome = ""

// confDir contains all configuration files to be generated by canaveral
// * tested
const confDir = "/canaveral/config/"
const wsFName = "cnavrlws"
const testFile = "canaveral_test_file"
